Add Python 3.13 to GitHub Actions CI

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -42,7 +42,7 @@ jobs:
       fail-fast: false
       matrix:
         os: [ 'ubuntu-24.04', 'ubuntu-22.04' ]
-        python: [ '3.12', '3.11', '3.10', '3.9','3.8' ]
+        python: [ '3.13', '3.12', '3.11', '3.10', '3.9', '3.8' ]
 
     runs-on: ${{ matrix.os }}
     name: Python ${{ matrix.python }} on ${{ matrix.os }}
@@ -62,19 +62,19 @@ jobs:
 
       - name: Install Python core deps (3.8 — 3.11)
         run: python -m pip install -r requirements.txt
-        if: ${{ matrix.python != '3.12' }}
+        if: ${{ (matrix.python != '3.12') && (matrix.python != '3.13') }}
 
       - name: Install Python testing deps (3.8 — 3.11)
         run: python -m pip install -r requirements-test.txt
-        if: ${{ matrix.python != '3.12' }}
+        if: ${{ (matrix.python != '3.12') && (matrix.python != '3.13') }}
 
-      - name: Install Python core deps (3.12)
+      - name: Install Python core deps (3.12 — 3.13)
         run: python -m pip install -r requirements-3.12.txt
-        if: ${{ matrix.python == '3.12' }}
+        if: ${{ (matrix.python == '3.12') || (matrix.python == '3.13') }}
 
-      - name: Install Python testing deps (3.12)
+      - name: Install Python testing deps (3.12 — 3.13)
         run: python -m pip install -r requirements-3.12-test.txt
-        if: ${{ matrix.python == '3.12' }}
+        if: ${{ (matrix.python == '3.12') || (matrix.python == '3.13') }}
 
       - name: Run Python tests
         run: make py-test
@@ -86,9 +86,10 @@ jobs:
         run: make pytype-test
         # https://github.com/google/pytype/issues/1475
         #
-        # PyType does not yet support Python 3.12; if this step is enabled, it
-        # fails with an error: "Python versions > 3.11 are not yet supported."
-        if: ${{ matrix.python != '3.12' }}
+        # PyType does not yet support Python 3.12 or later; if this step is
+        # enabled, it fails with an error: "Python versions > 3.11 are not yet
+        # supported."
+        if: ${{ (matrix.python != '3.12') && (matrix.python != '3.13') }}
 
       - name: Run nbconvert test
         run: make nbconvert-test
